name: SLO Configuration
description: Configure a Service Level Objective in Datadog
title: "[SLO]: "
labels: ["slo", "configuration"]
body:
  - type: input
    id: slo-name
    attributes:
      label: SLO Name
      description: What is the name of the SLO?
      placeholder: Example Metric SLO
    validations:
      required: true
  - type: input
    id: slo-description
    attributes:
      label: SLO Description
    validations:
      required: true
  - type: input
    id: numerator-query
    attributes:
      label: Numerator Query
      description: Enter the numerator for the SLO query.
      placeholder: sum:my.custom.count.metric{type:good_events}.as_count()
    validations:
      required: true
  - type: input
    id: denominator-query
    attributes:
      label: Denominator Query
      description: Enter the denominator for the SLO query.
      placeholder: sum:my.custom.count.metric{*}.as_count()
    validations:
      required: true
  - type: input
    id: thresholds-7d
    attributes:
      label: 7-day Thresholds
      description: Enter the target and warning thresholds for a 7-day timeframe.
      placeholder: "Target: 99.9, Warning: 99.99"
    validations:
      required: true
  - type: input
    id: thresholds-30d
    attributes:
      label: 30-day Thresholds
      description: Enter the target and warning thresholds for a 30-day timeframe.
      placeholder: "Target: 99.9, Warning: 99.99"
    validations:
      required: true
  - type: checkboxes
    id: tags
    attributes:
      label: Tags
      description: Select the tags that apply to this SLO.
      options:
        - label: foo:bar
        - label: baz
