name: Datadog SLO Configuration

on:
  issues:
    types: [opened, edited]

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name: File Run
        run: |
          echo "${{ github.event.issue.body }}" >> slo.txt

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.2'

      - name: Run Go Code
        run: |
          go run main.go slo.txt
