name: Datadog SLO Configuration

on:
  issues:
    types: [opened, edited]
  push:
    branches:
      - '**'

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Create SLO File
        run: |
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue.body }}" > slo.txt

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Run Go Code
        run: go run main.go slo.txt

      - name: Echo TF Code
        run: cat slo.tf

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a new branch
          git checkout -b auto-generated-slo-tf-$(date +%s)
          git add slo.tf
          git commit -m "Auto-generated slo.tf file"
          git push origin auto-generated-slo-tf-$(date +%s)

          # Install GitHub CLI
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          # Create a pull request
          gh pr create --title "Auto-generated slo.tf" --body "This is an auto-generated PR with the slo.tf file" --head auto-generated-slo-tf-$(date +%s) --base main

      
