name: Datadog SLO Configuration

on:
  issues:
    types: [opened, edited]

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          echo "${{ github.event.issue.body }}" >> slo.txt
          cat slo.txt
